export const serviceMeta = {
  water: { name: 'Водоснабжение', accent: 'cyan' },
  gas: { name: 'Газоснабжение', accent: 'gas' },
  electricity: { name: 'Электроснабжение', accent: 'yellow' },
};

export const initialStore = {
  users: [
    {
      id: 'payer-1',
      role: 'payer',
      name: 'Ирина Волкова',
      email: '1@gmail.com',
      password: '111111',
      phone: '+7 900 123-45-67',
      accountId: 'acc-1',
    },
    {
      id: 'employee-dispatcher',
      role: 'employee',
      name: 'Анна Сергеева',
      email: '1@gmail.com',
      password: '111111',
      loginName: 'dispatcher',
      employeeRole: 'Диспетчер',
      position: 'Диспетчер абонентской службы',
    },
    {
      id: 'company-admin-demo',
      role: 'companyAdmin',
      orgId: 'org-demo',
      name: 'Иван Петров',
      email: '1@gmail.com',
      password: '111111',
      phone: '+7 900 555-44-33',
    },
  ],
  accounts: [
    {
      id: 'acc-1',
      number: '407900000001',
      ownerName: 'Ирина Волкова',
      address: 'г. Казань, ул. Светлая, 18',
    },
    {
      id: 'acc-2',
      number: '407900000002',
      ownerName: 'Демо-абонент',
      address: 'г. Казань, ул. Озерная, 6',
    },
  ],
  receipts: [
    {
      id: 'rcp-1',
      accountId: 'acc-1',
      period: 'Январь 2026',
      service: 'water',
      amount: 1420,
      status: 'paid',
      dueDate: '2026-02-10',
      paidAt: '2026-02-04',
      method: 'СБП',
    },
    {
      id: 'rcp-2',
      accountId: 'acc-1',
      period: 'Январь 2026',
      service: 'electricity',
      amount: 2380,
      status: 'paid',
      dueDate: '2026-02-10',
      paidAt: '2026-02-06',
      method: 'МИР',
    },
    {
      id: 'rcp-3',
      accountId: 'acc-1',
      period: 'Февраль 2026',
      service: 'gas',
      amount: 960,
      status: 'paid',
      dueDate: '2026-03-10',
      paidAt: '2026-03-07',
      method: 'СБП',
    },
    {
      id: 'rcp-4',
      accountId: 'acc-1',
      period: 'Март 2026',
      service: 'electricity',
      amount: 2480,
      status: 'paid',
      dueDate: '2026-04-10',
      paidAt: '2026-04-08',
      method: 'МИР',
    },
    {
      id: 'rcp-5',
      accountId: 'acc-1',
      period: 'Март 2026',
      service: 'water',
      amount: 1510,
      status: 'paid',
      dueDate: '2026-04-10',
      paidAt: '2026-04-09',
      method: 'СБП',
    },
    {
      id: 'rcp-6',
      accountId: 'acc-2',
      period: 'Январь 2026',
      service: 'water',
      amount: 1110,
      status: 'paid',
      dueDate: '2026-02-10',
      paidAt: '2026-02-02',
      method: 'СБП',
    },
    {
      id: 'rcp-7',
      accountId: 'acc-2',
      period: 'Февраль 2026',
      service: 'gas',
      amount: 870,
      status: 'paid',
      dueDate: '2026-03-10',
      paidAt: '2026-03-08',
      method: 'МИР',
    },
  ],
  payments: [
    { id: 'pay-1', receiptId: 'rcp-1', method: 'СБП', paidAt: '2026-02-04', amount: 1420 },
    { id: 'pay-2', receiptId: 'rcp-2', method: 'МИР', paidAt: '2026-02-06', amount: 2380 },
    { id: 'pay-3', receiptId: 'rcp-3', method: 'СБП', paidAt: '2026-03-07', amount: 960 },
    { id: 'pay-4', receiptId: 'rcp-4', method: 'МИР', paidAt: '2026-04-08', amount: 2480 },
    { id: 'pay-5', receiptId: 'rcp-5', method: 'СБП', paidAt: '2026-04-09', amount: 1510 },
    { id: 'pay-6', receiptId: 'rcp-6', method: 'СБП', paidAt: '2026-02-02', amount: 1110 },
    { id: 'pay-7', receiptId: 'rcp-7', method: 'МИР', paidAt: '2026-03-08', amount: 870 },
  ],
};

export function getFreshStore() {
  return structuredClone(initialStore);
}
